info:
  contact: {}
  description: API service Core d'Eduva
  title: Eduva Core
  version: "1.0"
paths: {}
schemes:
- https
securityDefinitions:
  BearerAuth:
    in: headers
    name: Authorization
    type: apiKey
swagger: "2.0"
